### ISSUE TITLE
Capitilization of recommendations change, documentation change request.

### ISSUE THREAD

**Issue by YesterdaysCoffee** [Frix-x/klippain-shaketune#104]
### Describe the feature or hardware support you'd like

#1:  I love this utility and thank you for your work, please keep that in mind with what follows.
Ya well I'm dumb and didn't know 3HUMP_EI wasn't going to fly, but that is what the recommendation said to use.  Klipper said Nuh-uh!  Yahoo search told me to use lower case.

Perhaps the recommendation should use 3hump_ei for a recommendation to keep dumb people like me less frustrated.

### Additional context or information

none

**Comment by Frix-x** [comment]
This might be doable yes :)
I'll add this in the next release!
