### ISSUE TITLE
vibrations - Error while generating the graphs

### ISSUE THREAD

**Issue by krautech** [Frix-x/klippain-shaketune#109]
### K-Shake&Tune module branch

- [X] I confirm using the main branch

### Version

v3.0.0-1-g56a5502d

### Describe the bug and expected behavior

12:59 AM
Command {shaketune} finished
12:59 AM
Shake&Tune version: v3.0.0-1-g56a5502
Error while generating the graphs: File /home/chris/printer_data/config/K-ShakeTune_results/vibrations/vibrations_20240525_005253_vibrations-axemap.csv.csv does not match expected format. Clean your /tmp folder and start again!
12:59 AM
File "/home/chris/klippain_shaketune/src/is_workflow.py", line 408, in main
graph_creator.create_graph()
File "/home/chris/klippain_shaketune/src/is_workflow.py", line 320, in create_graph
fig = vibrations_profile(
^^^^^^^^^^^^^^^^^^^
File "/home/chris/klippain_shaketune/src/graph_creators/graph_vibrations.py", line 654, in vibrations_profile
angle, speed = extract_angle_and_speed(logname)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/home/chris/klippain_shaketune/src/graph_creators/graph_vibrations.py", line 626, in extract_angle_and_speed
raise ValueError(f'File {logname} does not match expected format. Clean your /tmp folder and start again!')
ValueError: File /home/chris/printer_data/config/K-ShakeTune_results/vibrations/vibrations_20240525_005253_vibrations-axemap.csv.csv does not match expected format. Clean your /tmp folder and start again!
12:59 AM
Traceback (most recent call last):
12:52 AM
Running Command {shaketune}...:
12:52 AM
This may take some time (3-5min)

---------------------------------------------------------

All I had done was run the "create vibrations profile" macro button on mainsail.
It looks like it named all the files it created as xxxxxxxxxxxxxxxxxxxxxxxxxxx.csv.csv

### Additional information and klippy.log

[klippy(2).log](https://github.com/Frix-x/klippain-shaketune/files/15436374/klippy.2.log)

**Comment by Frix-x** [comment]
Hello, this error is linked to #99 : the AXES_MAP_CALIBRATION leave some CSV artefacts and fail. Then these artefacts are found by the vibration measurement tool but that will be solved in the next version.

In the meantime, just reboot the Pi to clean the /tmp folder and don't use the AXES_MAP_CALIBRATION command: the other commands should work correctly :)
