### ISSUE TITLE
Allow DangerKlipper limited kinematics

### ISSUE THREAD

**Issue by PhilippMolitor** [Frix-x/klippain-shaketune#118]
### Describe the feature or hardware support you'd like

Should be exactly the same as their corresponding default kinematics:
https://dangerklipper.io/Config_Reference.html?h=kine#corexy-kinematics-with-limits-for-x-and-y-axes
The check just fails for limited_* kinematics.

**Comment by Frix-x** [comment]
I'll look into it. Thanks for the suggestion

**Comment by Frix-x** [comment]
This is currently merged in the develop branch and is planned for the next release :)
