### ISSUE TITLE
Internal error on command:"AXES_SHAPER_CALIBRATION"

### ISSUE THREAD

**Issue by huskyte** [Frix-x/klippain-shaketune#121]
### K-Shake&Tune module branch

- [X] I confirm using the main branch

### Version

v4.0.0-1-g8b0862a9

### Describe the bug and expected behavior

Message: Internal error on command:"AXES_SHAPER_CALIBRATION", whenever I try to run any command of Klippain through a macro. It was working before I upgraded and I followed the instructions for the update (hopefully).
The log is 23 MB, so I wouldn't want to attach it (oh, hell, it worked, so enjoy a few pages of reading there)

### Additional information and klippy.log

[klippy.log](https://github.com/user-attachments/files/15847207/klippy.log)

**Comment by Frix-x** [comment]
Klipper fail on this error : `KeyError: 'minimum_cruise_ratio'`

This means that you are running a pretty old version of Klipper and that you will need to update to a newer version where this parameter was added. It should fix your problem :)
