### ISSUE TITLE
Missing macros and cfg file?

### ISSUE THREAD

**Issue by vagudo** [Frix-x/klippain-shaketune#126]
### K-Shake&Tune module branch

- [X] I confirm using the main branch

### Version

??

### Describe the bug and expected behavior

I am new to Shake'n'tune but I used it a couple of weeks ago and discovered my belts were unequal. I fixed this and got to troubleshooting some other things. After running some updates today I can't find the macros, and digging a bit more I can't even fine any .cfg regarding shake'n'tune...
I have tried running the install command on Putty but no luck.

What do I do?

**Comment by Frix-x** [comment]
Please read the release notes from v4.0.0 : https://github.com/Frix-x/klippain-shaketune/releases
This version contain a breaking change due to the fact that it is now a Klipper plugin. Doing the required actions should fix your problem :)

**Comment by vagudo** [comment]
You are a rock star!!
