### ISSUE TITLE
Out of bounds error. Error while generating the graphs: index 147 is out of bounds for axis 0 with size 125 

### ISSUE THREAD

**Issue by kot0005** [Frix-x/klippain-shaketune#130]
### K-Shake&Tune module branch

- [X] I confirm using the main branch

### Version

latest that is built into klipper

### Describe the bug and expected behavior

fails to convert csv files to png
[klippy (6).log](https://github.com/user-attachments/files/15901399/klippy.6.log)
![image](https://github.com/Frix-x/klippain-shaketune/assets/68181325/4cf5f953-530d-4dbe-ae88-bc9a516abec8)
![image](https://github.com/Frix-x/klippain-shaketune/assets/68181325/f858ecac-727f-49bf-b29f-a022f2256fee)

Also the belt comparison test varies by a lot run to run.

**Comment by Frix-x** [comment]
Hello, I've pushed a fix for a potential bug in the CSV file writing function in v4.0.2 and your issue might be solved. Could you please update and let me know if it's still a problem?

**Comment by Frix-x** [comment]
Hello, this was solved in v4.1.0
