### ISSUE TITLE
Huge variability in Belt tension results If Shake tune in run back to beak without a hard reboot.

### ISSUE THREAD

**Issue by kot0005** [Frix-x/klippain-shaketune#133]
### K-Shake&Tune module branch

- [X] I confirm using the main branch

### Version

4.0.0-2-gfb8e1ce

### Describe the bug and expected behavior

I am getting very wild results in Belt tuning results if I run it back to back. Sometimes the Estimated similarity can swing to upto -10,000%

Rebooting before another run, seems to fix this issue.

![image](https://github.com/Frix-x/klippain-shaketune/assets/68181325/456b21d9-27d6-4ff3-90a7-6c59496de8f3)

[klippy (7).log](https://github.com/user-attachments/files/15970740/klippy.7.log)

![image](https://github.com/Frix-x/klippain-shaketune/assets/68181325/e72f69f4-7040-47d3-8b0b-3d84c68725f5)

![image](https://github.com/Frix-x/klippain-shaketune/assets/68181325/d1e16e5b-e63e-444a-b047-bc2c9b43f25a)

![image](https://github.com/Frix-x/klippain-shaketune/assets/68181325/243f3b6b-c915-4c72-976d-ef8952591c48)

**Comment by Frix-x** [comment]
Can you share the full picture please (and the CSVs if you have them?)?

I would like to see how the graphs looks to understand why these numbers...

**Comment by kot0005** [comment]
> Can you share the full picture please (and the CSVs if you have them?)?
> 
> I would like to see how the graphs looks to understand why these numbers...

Hi, where are the CSV files stored in the new version of Klippain shake tune ?

unfortunately i don't have all the graphs showing the -ve XXXXX% values. I found one which has a -115% similarity.

I only have the +ve XX% value graphs now. I have been rebooting Klipper every attempt, Which fixed the issue -ve % graphs in the 100's to 1000's

![image](https://github.com/Frix-x/klippain-shaketun
![beltscomparison_20240623_133134](https://github.com/Frix-x/klippain-shaketune/assets/68181325/84217718-6051-4188-87be-ea8c4da54eed)
e/assets/68181325/db095e2f-9c6e-4f0c-83b8-389842ac1f19)
![image](https://github.com/Frix-x/klippain-shaketune/assets/68181325/f697bcca-faa9-4024-9515-c82ddd416f7c)

![image](https://github.com/Frix-x/klippain-shaketune/assets/68181325/a0be5c21-eb3e-4350-ae26-4aae15a47da2)

**Comment by Frix-x** [comment]
Hello, thanks for sharing this. The issue should be solved in v4.1.0 as small bugfixes were done on the belt graph and how the similarity is computed :)
