### ISSUE TITLE
Error Installing collected packages: matplotlib, GitPython

### ISSUE THREAD

**Issue by AmshaSharam** [Frix-x/klippain-shaketune#142]
### K-Shake&Tune module branch

- [X] I confirm using the main branch

### Version

v4.1.0

### Describe the bug and expected behavior

i get this error on instalation:
Installing collected packages: matplotlib, GitPython
ERROR: Could not install packages due to an OSError: [Errno 13] Permission denied: '/home/pi/klippy-env/lib/python3.9/site-packages/mpl_toolkits/axes_grid1/__init__.py'
Check the permissions.

**Comment by Frix-x** [comment]
Hello,

I think you are running RatOS. If that's the case, then it's a known bug on their side that was already raised to them.
See here https://github.com/Frix-x/klippain-shaketune/issues/116 for more information

**Comment by AmshaSharam** [comment]
You are right, thank you.
