### ISSUE TITLE
Upgrading from verison 3.001 to version 4.1.01 causes macros to disapear from fluid macro console,

### ISSUE THREAD

**Issue by pmbroth** [Frix-x/klippain-shaketune#145]
### K-Shake&Tune module branch

- [X] I confirm using the main branch

### Version

3.0.0-1-g56a5502d 

### Describe the bug and expected behavior

When I upgrtade from 3.0.0-1-g56a5502d  to latest version via fluid, all macros disapear, and I cannot find them any where.  They are removed from the  fluid macro console. I looked though my macro config file and  there are no macro definitions  for the Klippain-shaketune.

**Comment by Frix-x** [comment]
This is normal and due to a breaking change: v4 is now a fully integrated plugin into Klipper and you should start gain the install script manually. See here for more info: https://github.com/Frix-x/klippain-shaketune/releases/tag/v4.0.0

**Comment by pmbroth** [comment]
Perfect thank you - Works perfectly can be closed!!
