### ISSUE TITLE
running Axis Map Calibration - stops with error

### ISSUE THREAD

**Issue by pmbroth** [Frix-x/klippain-shaketune#146]
### K-Shake&Tune module branch

- [X] I confirm using the main branch

### Version

v3.0.0-1-g56a5502d 

### Describe the bug and expected behavior

This is what happens see below:
 
$ AXES_MAP_CALIBRATION
10:51:29 
// 
10:51:29 
// Starting accelerometer axe_map calibration
10:51:29 
// This operation can not be interrupted by normal means. Hit the "emergency stop" button to stop it if needed
10:51:29 
// 
10:51:29 
// accelerometer measurements started
10:51:36 
// Writing raw accelerometer data to /tmp/adxl345-axemap.csv file
10:51:36 
echo: Analysis of the movements...
10:51:36 
// Running Command {shaketune}...:
10:51:41 
// Traceback (most recent call last):
10:51:41 
// File "/home/mks/klippain_shaketune/src/is_workflow.py", line 408, in main
// graph_creator.create_graph()
// ^^^^^^^^^^^^^^^^^^^^^^^^^^
// AttributeError: 'AxesMapFinder' object has no attribute 'create_graph'
10:51:41 
// Shake&Tune version: v3.0.0-1-g56a5502
// Error while generating the graphs: 'AxesMapFinder' object has no attribute 'create_graph'
10:51:42 
// Command {shaketune} finished

**Comment by Frix-x** [comment]
This issue is solved starting from v4.0.0.
So just update S&T and you should be good to go. Be aware of the breaking change that needs to be taken into account when going to v4+ : https://github.com/Frix-x/klippain-shaketune/releases/tag/v4.0.0

**Comment by pmbroth** [comment]
Thank you!!!
