### ISSUE TITLE
Install script fails if klipper service using non-default name

### ISSUE THREAD

**Issue by HenryJia** [Frix-x/klippain-shaketune#156]
### K-Shake&Tune module branch

- [X] I confirm using the main branch

### Version

66f5e32e4c8930afab278fcd898b47c227cc464c

### Describe the bug and expected behavior

For cases such as running multiple klipper instances with KIAUH, the klipper service names aren't just klipper.service. This causes the install script to fail to find klipper

**Comment by Frix-x** [comment]
Hello, there's this PR under work to allow this: https://github.com/Frix-x/klippain-shaketune/pull/154
