### ISSUE TITLE
Reports not visible in mainsail

### ISSUE THREAD

**Issue by TxBillbr** [Frix-x/klippain-shaketune#158]
### K-Shake&Tune module branch

- [X] I confirm using the main branch

### Version

v4.1.0-1-g66f5e32e

### Describe the bug and expected behavior

Going to mainsail dropdown of machine/configs and choosing ShakeTune_results shows files, but clicking on a result returns a 404. Inspecting the structure on the pi shows that the results are in a subdirectory by macro. This may be a mailsail bug. This problem  makes it hard for the user to find the output and see it (especially if they are not fascile with linux). Simply copying the files on the pi from the subdirectory to the directory above makes the reports visible in the mainsail UI. For what its worth I resorted to checking the sources to find where the output was written as I could not find any reference to where the output should be in the documentation.

**Comment by Frix-x** [comment]
Hello!

This is a known issue with Mainsail that is super easy to fix: restart your web browser or clear your browser cache. The files should then display correctly.

Note: Fluidd doesn't seem to have this problem.
