### ISSUE TITLE
Error on manual install (in multi-klipper instances)

### ISSUE THREAD

**Issue by islonina** [Frix-x/klippain-shaketune#167]
### K-Shake&Tune module branch

- [X] I confirm using the main branch

### Version

v4.1.0-1-g66f5e32e

### Describe the bug and expected behavior

On manual install(change only direcotry for config folder and name of the moonraker and klipper-multi instance install) i on very end i got :
gcode command EXCITATE_AXIS_AT_FREQ already registered

Its from dummy macro for placing Buttons in UI

**Comment by islonina** [comment]
[klippy (2).log](https://github.com/user-attachments/files/17435357/klippy.2.log)

**Comment by Frix-x** [comment]
Hello, multi-klipper instances are not officially supported at the moment... So it will be very difficult to help you debug this as the install script wasn't used.

Support is planned in the future.
