### ISSUE TITLE
Shaketune not working after klipper update

### ISSUE THREAD

**Issue by DVSVIDEO** [Frix-x/klippain-shaketune#177]
### K-Shake&Tune module branch

- [X] I confirm using the main branch

### Version

v4.1.0-1-g66f5e32e

### Describe the bug and expected behavior

Shaketune not working after klipper update: v0.12.0-401-g383b83d7

**Comment by DocFoFo** [comment]
Use this to apply the fix thats been pushed so far...

https://github.com/Frix-x/klippain-shaketune/issues/172#issuecomment-2557697430

**Comment by Frix-x** [comment]
This is indeed a duplicate of #172 . I'll close this issue in favor of the other one :)
