### ISSUE TITLE
ERROR  after update Option 'keep_raw_csv' is not valid in section 'shaketune'

### ISSUE THREAD

**Issue by Byourei** [Frix-x/klippain-shaketune#184]
### K-Shake&Tune module branch

- [X] I confirm using the main branch

### Version

v5.0.0-0-g74364d72

### Describe the bug and expected behavior

Option 'keep_raw_csv' is not valid in section 'shaketune'

Once the underlying issue is corrected, use the "RESTART"
command to reload the config and restart the host software.
Printer is halted

what it this?

**Comment by thiagogssantos** [comment]
I had the same problem,
check out the "readme" , some settings need to be changed in printer.cfg

**Comment by DVSVIDEO** [comment]
You didn't read that you need to copy new settings into printer.cfg instead of the old ones.

**Comment by Byourei** [comment]
Thank you
