### ISSUE TITLE
Error running command {shaketune}

### ISSUE THREAD

**Issue by Dejv1cz** [Frix-x/klippain-shaketune#25]
### K-Shake&Tune module branch

- [X] I confirm using the main branch

### Version

v2.0.0

### Describe the bug and expected behavior

Everything starts up fine
csv files are created and written
but then it says: Error running command {shaketune}

**Comment by Frix-x** [comment]
Can you add more info like the log and what is displayed in the console? It will be pretty hard for me to debug it without these information

**Comment by Mike-Gough** [comment]
I had the same issue and eventually worked it out. What seemed to fix it for me is the installer put everything in `~/printer_data/config/scripts/K-ShakeTune` and after I moved it to the parent folder `~/printer_data/config/K-ShakeTune` I no longer got the error

**Comment by Dejv1cz** [comment]
I tried to remove and reinstall everything and suddenly it works

**Comment by Frix-x** [comment]
Oh ok, this is strange. I'll have a look to see how that's possible... But I'll close this issue if everything is running fine for you now :)

**Comment by dragoonmc** [comment]
I had a similar experience. might be from me adding the K-ShakeTune folder to the config folder while installing. also was missing the scripts in Klippain folder.
I am on a CB1 instead of a Pi if that makes any difference
