### ISSUE TITLE
Problem installing

### ISSUE THREAD

**Issue by pauluchin** [Frix-x/klippain-shaketune#30]
### K-Shake&Tune module branch

- [X] I confirm using the main branch

### Version

V 2.0.0

### Describe the bug and expected behavior

1rt time installing... and tried from the installation I had and with a clean installation.
I always get the same error

If you could help me I would appreciate it very much.

### Additional information and klippy.log

 Building wheels for collected packages: ninja
        Building wheel for ninja (pyproject.toml): started
        Building wheel for ninja (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        × Building wheel for ninja (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [13 lines of output]
            /tmp/pip-build-env-k2ikoigz/overlay/lib/python3.9/site-packages/setuptools_scm/git.py:308: UserWarning: git archive did not support describe output
              warnings.warn("git archive did not support describe output")
            /tmp/pip-build-env-k2ikoigz/overlay/lib/python3.9/site-packages/setuptools_scm/git.py:327: UserWarning: unprocessed git archival found (no export subst applied)
              warnings.warn("unprocessed git archival found (no export subst applied)")
            Traceback (most recent call last):
              File "/tmp/pip-build-env-k2ikoigz/overlay/lib/python3.9/site-packages/skbuild/setuptools_wrap.py", line 645, in setup
                cmkr = cmaker.CMaker(cmake_executable)
              File "/tmp/pip-build-env-k2ikoigz/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 148, in __init__
                self.cmake_version = get_cmake_version(self.cmake_executable)
              File "/tmp/pip-build-env-k2ikoigz/overlay/lib/python3.9/site-packages/skbuild/cmaker.py", line 105, in get_cmake_version
                raise SKBuildError(msg) from err

            Problem with the CMake installation, aborting build. CMake executable is cmake
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for ninja
      Failed to build ninja
      ERROR: Could not build wheels for ninja, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install backend dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

**Comment by Frix-x** [comment]
Hello, can you tell me which OS is this and which board?

The error you have is probably due to CMake not installed or some dependencies missing (CMake is used to compile some C code needed by Numpy if there is no precompilled binarry available for your OS/Pi combo).

I would try to install CMake manually first and update pip and wheel:

```bash
apt update
apt install cmake -y

source ~/klippain_shaketune-env/bin/activate
pip install --upgrade pip
pip install --upgrade setuptools wheel
deactivate
```

Then start again the install script and let me know if it's ok
