### ISSUE TITLE
Idea: put default amount of keep_results into a variables file

### ISSUE THREAD

**Issue by Zeanon** [Frix-x/klippain-shaketune#47]
### Describe the feature or hardware support you'd like

I think it would be nice, to be able to alter the default amount of keep_results without having to specify it in the command every time.
Solution would be rather easy, have one variable file, that gets copied instead of symlinked and the install script checks whether it already exists (if not, it gets copied, if it exists, it wont)
(I can do a pr for it, just wanted to check whether you would even consider it first)

**Comment by Zeanon** [comment]
> Hi, thanks for the suggestion, and yes this is something already in my backlog. It was just not the priority but I definitely want to add this.
> 
> I'm really open for a PR if you want to work on this :) Also, at the same time I wanted to have the accelerometer chip name and the "keep_csv" in this variable in the same way. And maybe define a main read-only file as a simlink with default value that one could copy paste and override in his config if needed. What do you think about this? It would make it easier for updates and avoid potential breaking changes.

Sounds good, havent thought about those two as well but makes sense to also make them "static"
I would also add a version variable to it which gets checked on startup, to prevent mishaps (like I am doing here: https://github.com/LynxCrew/Klicky/blob/main/Variables/homing_variables.cfg)
I'll get to it later and write the code for it

**Comment by Zeanon** [comment]
PR is out

**Comment by Surion79** [comment]
could you please link your PR to the issue or vice versa? Thanks :)

**Comment by Frix-x** [comment]
@Surion79 #48
