### ISSUE TITLE
ModuleNotFoundError: No module named 'git'

### ISSUE THREAD

**Issue by Experiment4** [Frix-x/klippain-shaketune#50]
### K-Shake&Tune module branch

- [X] I confirm using the main branch

### Version

v2.5.0-0-g84c406b4

### Describe the bug and expected behavior

I installed shaketune and included the .cfg in my pritner.cfg. I can run shaketune, but there is no final outcome.
I just installed the shaketune, not the klippain feature.

those are some of the files found in the directory 
  8 -rwxr-xr-x 1 tom tom   5985 10. Jan 20:55 analyze_axesmap.py
  8 -rw-r--r-- 1 tom tom   5075 10. Jan 20:55 common_func.py
 24 -rwxr-xr-x 1 tom tom  23446 10. Jan 20:55 graph_belts.py

I use :
Klippain-ShakeTune
v2.5.0-0-g84c406b4
Computer:
Intel(R) Celeron(R) J4105 CPU @ 1.50GHz
7.5 GB
64bit x86_64 with 4 cores
Debian GNU/Linux 11 (bullseye)

### Additional information and klippy.log

Writing raw accelerometer data to /tmp/raw_data_y_y.csv file
Running Command {shaketune}...:
ADXL345 finished 'adxl345' measurements
Stats 17379.8: gcodein=0  mcu: mcu_awake=0.284 mcu_task_avg=0.000005 mcu_task_stddev=0.000004 bytes_write=3864725 bytes_read=1026706 bytes_retransmit=0 bytes_invalid=0 send_seq=82677 receive_seq=82677 retransmit_seq=0 srtt=0.000 rttvar=0.000 rto=0.025 ready_bytes=0 upcoming_bytes=0 freq=180001868 sht36: mcu_awake=1.122 mcu_task_avg=0.000048 mcu_task_stddev=0.000028 bytes_write=149210 bytes_read=5439105 bytes_retransmit=0 bytes_invalid=0 send_seq=10139 receive_seq=10139 retransmit_seq=0 srtt=0.001 rttvar=0.000 rto=0.025 ready_bytes=0 upcoming_bytes=0 freq=48000279 adj=47999626  CPU_SHT36: temp=40.9 heater_bed: target=55 temp=55.2 pwm=0.095 Octopus_MCU: temp=38.7 sysload=0.50 cputime=375.847 memavail=6819652 print_time=1805.114 buffer_time=0.000 print_stall=14 extruder: target=200 temp=200.2 pwm=0.372
Stats 17380.8: gcodein=0  mcu: mcu_awake=0.217 mcu_task_avg=0.000005 mcu_task_stddev=0.000004 bytes_write=3864899 bytes_read=1027117 bytes_retransmit=0 bytes_invalid=0 send_seq=82690 receive_seq=82690 retransmit_seq=0 srtt=0.000 rttvar=0.000 rto=0.025 ready_bytes=0 upcoming_bytes=0 freq=180001806 sht36: mcu_awake=0.918 mcu_task_avg=0.000048 mcu_task_stddev=0.000028 bytes_write=149244 bytes_read=5439272 bytes_retransmit=0 bytes_invalid=0 send_seq=10142 receive_seq=10142 retransmit_seq=0 srtt=0.001 rttvar=0.000 rto=0.025 ready_bytes=0 upcoming_bytes=0 freq=48000275 adj=47999827  CPU_SHT36: temp=40.8 heater_bed: target=55 temp=55.1 pwm=0.095 Octopus_MCU: temp=38.8 sysload=0.50 cputime=375.875 memavail=6761740 print_time=1805.114 buffer_time=0.000 print_stall=14 extruder: target=200 temp=200.2 pwm=0.372
Traceback (most recent call last):
  File "/home/tom/klippain_shaketune/K-ShakeTune/scripts/is_workflow.py", line 26, in <module>

    from graph_belts import belts_calibration
  File "/home/tom/klippain_shaketune/K-ShakeTune/scripts/graph_belts.py", line 25, in <module>
    from common_func import compute_spectrogram, detect_peaks, get_git_version, parse_log, setup_klipper_import
  File "/home/tom/klippain_shaketune/K-ShakeTune/scripts/common_func.py", line 12, in <module>
    from git import GitCommandError, Repo
ModuleNotFoundError: No module named 'git'

Command {shaketune} finished

Running Command {shaketune}...:
Stats 17381.8: gcodein=0  mcu: mcu_awake=0.217 mcu_task_avg=0.000005 mcu_task_stddev=0.000004 bytes_write=3865089 bytes_read=1027501 bytes_retransmit=0 bytes_invalid=0 send_seq=82704 receive_seq=82704 retransmit_seq=0 srtt=0.000 rttvar=0.000 rto=0.025 ready_bytes=0 upcoming_bytes=0 freq=180001749 sht36: mcu_awake=0.918 mcu_task_avg=0.000048 mcu_task_stddev=0.000028 bytes_write=149278 bytes_read=5439450 bytes_retransmit=0 bytes_invalid=0 send_seq=10145 receive_seq=10145 retransmit_seq=0 srtt=0.001 rttvar=0.000 rto=0.025 ready_bytes=0 upcoming_bytes=0 freq=48000272 adj=48000016  CPU_SHT36: temp=40.8 heater_bed: target=55 temp=55.1 pwm=0.101 Octopus_MCU: temp=38.9 sysload=0.50 cputime=375.931 memavail=6921480 print_time=1805.114 buffer_time=0.000 print_stall=14 extruder: target=200 temp=200.2 pwm=0.372
Traceback (most recent call last):
  File "/home/tom/klippain_shaketune/K-ShakeTune/scripts/is_workflow.py", line 26, in <module>

    from graph_belts import belts_calibration
  File "/home/tom/klippain_shaketune/K-ShakeTune/scripts/graph_belts.py", line 25, in <module>
    from common_func import compute_spectrogram, detect_peaks, get_git_version, parse_log, setup_klipper_import
  File "/home/tom/klippain_shaketune/K-ShakeTune/scripts/common_func.py", line 12, in <module>
    from git import GitCommandError, Repo
ModuleNotFoundError: No module named 'git'

**Comment by lusl13** [comment]
[klippy (1).log](https://github.com/Frix-x/klippain-shaketune/files/13963841/klippy.1.log)
have same problem. 

Command {shaketune} finished
14:31
from git import GitCommandError, Repo
ModuleNotFoundError: No module named 'git'
14:31
from graph_belts import belts_calibration
File "/home/biqu/klippain_shaketune/K-ShakeTune/scripts/graph_belts.py", line 25, in
from common_func import compute_spectrogram, detect_peaks, get_git_version, parse_log, setup_klipper_import
File "/home/biqu/klippain_shaketune/K-ShakeTune/scripts/common_func.py", line 12, in
14:31
Traceback (most recent call last):
File "/home/biqu/klippain_shaketune/K-ShakeTune/scripts/is_workflow.py", line 26, in
14:31
Running Command {shaketune}...:
14:31
Command {shaketune} finished
14:31
from git import GitCommandError, Repo
ModuleNotFoundError: No module named 'git'
14:31
from graph_belts import belts_calibration
File "/home/biqu/klippain_shaketune/K-ShakeTune/scripts/graph_belts.py", line 25, in
from common_func import compute_spectrogram, detect_peaks, get_git_version, parse_log, setup_klipper_import
File "/home/biqu/klippain_shaketune/K-ShakeTune/scripts/common_func.py", line 12, in
14:31
Traceback (most recent call last):
File "/home/biqu/klippain_shaketune/K-ShakeTune/scripts/is_workflow.py", line 26, in
14:31
Running Command {shaketune}...:
14:31
This may take some time (1-3min)
14:31
Y axis frequency profile generation...
14:31
Writing raw accelerometer data to /tmp/raw_data_y_y.csv file
14:31
Re-enabled [input_shaper]
14:31
Testing frequency 133 Hz

**Comment by Frix-x** [comment]
Hello,

This happens when you update from an older version. There was a breaking change and you will find the solution in the release notes here: https://github.com/Frix-x/klippain-shaketune/releases/tag/v2.5.0

**Comment by Sonnenwerk** [comment]
Thanks, that helped. I thought i had klippain not installed before, but i did a lot of changes the last days ;)
