### ISSUE TITLE
Can't install to K1C

### ISSUE THREAD

**Issue by Psych0h3ad** [Frix-x/klippain-shaketune#64]
### K-Shake&Tune module branch

- [X] I confirm using the main branch

### Version

1.3.3.5

### Describe the bug and expected behavior

![image](https://github.com/Frix-x/klippain-shaketune/assets/41975091/e9d94ecf-edb0-4c11-b9ef-c6a9fd02aefb)

**Comment by Frix-x** [comment]
This is not an S&T error and look like you are using the wget command on an OS that doesn't have the proper certificate validation... I can't really help you but you will need to make wget work. Using `--no-check-certificate` option could be an idea.
