### ISSUE TITLE
After Running AXES_MAP_CALIBRATION i do not get the graphs

### ISSUE THREAD

**Issue by ghostv714** [Frix-x/klippain-shaketune#71]
### K-Shake&Tune module branch

- [x] I confirm using the main branch

### Version

v2.6.0-2-g312a9c9f 

### Describe the bug and expected behavior

when i call AXES_MAP_CALIBRATION. the test begins to completion i get no errors. then when it comes time to get the results and the pngs all i get is the cvs.
this is what i get when the printer is done moving:

- ` 10:13:24  // Command {shaketune} finished
- 10:13:23  // performance_shaper, shapers, calibration_data, fr, zeta = calibrate_shaper(datas[0], max_smoothing, scv, max_freq)
- // File "/home/biqu/klippain_shaketune/K-ShakeTune/scripts/graph_shaper.py", line 54, in calibrate_shaper
- // shaper, all_shapers = helper.find_best_shaper(
- // TypeError: find_best_shaper() got an unexpected keyword argument 'shapers'
- 10:13:23  // axis = create_shaper_graph(keep_csv=options.keep_csv, max_smoothing=options.max_smoothing, scv=options.scv)
- // File "/home/biqu/klippain_shaketune/K-ShakeTune/scripts/is_workflow.py", line 123, in create_shaper_graph
- // fig = shaper_calibration([new_file], KLIPPER_FOLDER, max_smoothing=max_smoothing, scv=scv)
- // File "/home/biqu/klippain_shaketune/K-ShakeTune/scripts/graph_shaper.py", line 217, in shaper_calibration
- 10:13:23  // main()
- // File "/home/biqu/klippain_shaketune/K-ShakeTune/scripts/is_workflow.py", line 289, in main
- 10:13:23  // Traceback (most recent call last):
- // File "/home/biqu/klippain_shaketune/K-ShakeTune/scripts/is_workflow.py", line 303, in
- 10:13:14  // Running Command {shaketune}...:
- 10:13:14  echo: This may take some time (1-3min)
- 10:13:14  echo: Y axis frequency profile generation...
- 10:13:14  // Writing raw accelerometer data to /tmp/raw_data_y_y.csv file
- 10:13:11  // Re-enabled [input_shaper]`
- 

### Additional information and klippy.log

[klippy.log](https://github.com/Frix-x/klippain-shaketune/files/14349934/klippy.log)

**Comment by M3HNGRY** [comment]
I'm getting same errors as well..

https://cdn.discordapp.com/attachments/1096701708643614820/1209707525155463168/image.png?ex=65e7e6ed&is=65d571ed&hm=17bb824f3f3e338a6489e1f69bbb7be8b853c9bddd53cf9ab0c41b66a54b4ffe&

https://cdn.discordapp.com/attachments/1096701708643614820/1209707632185712670/image.png?ex=65e7e706&is=65d57206&hm=9af3e6b93ee8d267c51e507c4d20478746f88ac6d836f6abd8a07b88d0df13ed&

**Comment by ghostv714** [comment]
You know I didn't think of it but I am running klipper on a BTT CB1. Would that have anything to do with my errors

**Comment by skyaee** [comment]
![QQ screenshot 20240301155617](https://github.com/Frix-x/klippain-shaketune/assets/40803751/0fecf4d9-b663-47c6-94a4-f6917154632a)
I have the latest version and have the same problem. I cannot display png. Is it because I switched to danger-klipper?

**Comment by dougshell** [comment]
I have the same behaviuor running the latest klipper

**Comment by Phil1988** [comment]
So did I get it right, that S&T is (in the latest version) not any more compatible to the latest klipper?

I think the last working version was v2.6.0 is this right?
Im asking because I think I may have this problem when perfoming "AXES_SHAPER_CALIBRATION":
![image](https://github.com/Frix-x/klippain-shaketune/assets/6054234/43e960f3-994b-49a6-81e0-1b42c0b52b12)

**Comment by MafiZed** [comment]
Same issue here on latest klipper, broken .png is all that appears. Any fix developed in this time?

**Comment by Extrutex** [comment]
> Dasselbe Problem hier beim neuesten Klipper, es wird nur eine defekte PNG-Datei angezeigt. Wurde inzwischen eine Lösung entwickelt?

 bei mir funktioniert alles mit dem neusten Klipper ! 
 mal einen  Hard Refresh gemacht ? 
Browser	Windows	macOS 
Chrome	Strg+F5	Command+Shift+R
Firefox	Strg+F5	Command+Shift+R
Safari	N/A	Option+Command+E (Leert Cache)

**Comment by Nino1683** [comment]
Proposed Fix
The calls to process_accelerometer_data need to be updated to include None as the first argument (name) to match the new Klipper signature.

I have manually patched the following files to fix the issue on my machine:

1. nano ~/klipper/klippy/extras/shaketune/graph_creators/computations/shaper_computation.py Change:
Old
calib_data = shaper_calibrate.process_accelerometer_data(datas)
New
calib_data = shaper_calibrate.process_accelerometer_data(None, datas)

2. nano ~/klipper/klippy/extras/shaketune/graph_creators/computations/vibrations_computation.py Change:
Old
freq_response = shaper_calibrate.process_accelerometer_data(data)
New
freq_response = shaper_calibrate.process_accelerometer_data(None, data)

3. nano ~/klipper/klippy/extras/shaketune/graph_creators/computations/belts_computation.py Change:
Old
calibration_data = shaper_calibrate.process_accelerometer_data(data)
New
calibration_data = shaper_calibrate.process_accelerometer_data(None, data)
After applying these changes and restarting Klipper, the graph generation works correctly.
