### ISSUE TITLE
None vs none in K-SnT_axis.cfg

### ISSUE THREAD

**Issue by diberben** [Frix-x/klippain-shaketune#72]
### K-Shake&Tune module branch

- [X] I confirm using the main branch

### Version

v2.6.0-0-g80c8da62

### Describe the bug and expected behavior

Hello,
after todays update got an error "loading template 'gcode_macro AXES_SHAPER_CALIBRATION:gcode': jinja2.exceptions.TemplateAssertionError: no test named 'None'". Changing "None" to "none" in K-SnT_axis.cfg fixed the error message. Havent run it yet, though.
Regards
Dirk

**Comment by Frix-x** [comment]
This error was solved 4 days ago in this commit: f4e700a1ffcbdf4e421d276734609ee69e9145f2
Update to the latest version (at least v2.6.0-1) to get it fixed :)

If you don't have it, validate that your moonraker.conf is correct (see here: https://github.com/Frix-x/klippain-shaketune/blob/main/moonraker.conf)
