### ISSUE TITLE
 ERROR: THESE PACKAGES DO NOT MATCH THE HASHES FROM THE REQUIREMENTS FILE. 

### ISSUE THREAD

**Issue by lunarconcepts** [Frix-x/klippain-shaketune#75]
### K-Shake&Tune module branch

- [X] I confirm using the main branch

### Version

v2.6.0

### Describe the bug and expected behavior

Hello, Thanks for your work on Shaketune . I am new to github format so I apologize if this isn't how to handle these issue. I am gettin the listed error when trying to add shaketune via putty. Maybe I am doing something wrong but seems you made it as easy as possible? 
![image](https://github.com/Frix-x/klippain-shaketune/assets/127275984/3323c2ed-a864-43d6-9936-b8c1ab911d4f)

**Comment by V1EngineeringInc** [comment]
I had that happen yesterday, it just installed fine today. Might want to give it another try.

Great software!

**Comment by lunarconcepts** [comment]
> I had that happen yesterday, it just installed fine today. Might want to give it another try.
> 
> Great software!

Thanks, I am up and running now!

**Comment by V1EngineeringInc** [comment]
Might want to close the issue, that helps out the dev.

**Comment by Frix-x** [comment]
This usually happens when the network connection is a bit unstable. Usually clearing the pip cache and trying again solve this issue :)
