### ISSUE TITLE
Does the Belts graph support four-motor awd?

### ISSUE THREAD

**Issue by skyaee** [Frix-x/klippain-shaketune#77]
### K-Shake&Tune module branch

- [X] I confirm using the main branch

### Version

v2.6.0-2-g312a9c9f

### Describe the bug and expected behavior

Does the Belts graph support four-motor awd?
Tested multiple times, with the same configuration unchanged, the test results have a large error.

**Comment by Frix-x** [comment]
This should work.

If it's not the case, then it means that Klipper doesn't support resonance testing using AWD since I use the standard Klipper command under the hood to do this.
