### ISSUE TITLE
Measure Fan Vibration

### ISSUE THREAD

**Issue by phpbbireland** [Frix-x/klippain-shaketune#85]
### Describe the feature or hardware support you'd like

Would it be possible to add Fan Vibration Testing and display results in an Image format?

Skirt Fans are not particularly quiet, they often vibrate and apart from the annoying noise, they must affect other measurements. 

It would be nice to have a tool to display graphically the impact of vibrating fans and results of adding various damping materials...

**Comment by henrivdr** [comment]
Double up vote on this one.

**Comment by Frix-x** [comment]
Hi, I'm not sure how to measure this in Shake&Tune as it would require a microphone or something like that and I can't compare it to a baseline. Also, skirt fans shouldn't have any effect on the prints...

As for the fans that do have an impact on prints (i.e. toolhead fans) and can produce VFAs, they are already recorded during the tests as you can see in the docs here: https://github.com/Frix-x/klippain-shaketune/blob/main/docs/macros/axis_tuning.md#fan-behavior

However, if you have a specific idea in mind, I'm open to it :)

**Comment by phpbbireland** [comment]
I guess we can close this...
